### ISSUE TITLE
Error generating job, try again: No answer for generate job                Report ID: G9D3eBAmhC

### ISSUE THREAD

**Issue by etherealcurls** [fetchfox/fetchfox#22]
Whenever I try to scrape something, whether it's something for my project or even using the examples listed, such as "sfbay.craigslist.org find number of bedrooms, bathrooms, 2-5 word summary", it pops up with : "Error generating job, try again: No answer for generate job"

**Comment by ortutay** [comment]
@etherealcurls are you using your own API key? If so can you try to run it using the "Free... For Now / Use Our Server" option, and see if that one works?

Sometimes these issues are a result of quota or credits.
