### ISSUE TITLE
Onboarding improvements

### ISSUE THREAD

**Issue by johnratezip** [fetchfox/fetchfox#4]
hey marcell, i wanted to test this out but had some trouble getting going. here are some thoughts for potential improvements:

1. readme does not explicitly say to add a .env file with OPENAI_API_KEY variable
2. instantiating the openapi client as suggested in the error message did not work, ie 
```
const client = new OpenAI({
  apiKey:
    "MY_API_KEY",
});
```
3. is the library already configured to minimize charges from openai? if no, what steps should be taken prior to scraping? readme doesn't say one way or the other

**Comment by ortutay** [comment]
@johnratezip I updated the readme based on your feedback, and I also pushed some changes here to make it easier to configure the AI. You can now do this:

```javascript
import { fox } from 'fetchfox';

const results = await fox
  .config({ ai: { model: 'openai:gpt-4o-mini', apiKey: 'sk-your-key' }})
  .run(`https://news.ycombinator.com/news find links to comments, get basic data, export to out.jsonl`);
```

Let me know if these changes help.

**Comment by johnratezip** [comment]
yep this is perfect, closing the issue
